### ISSUE TITLE
pretrained HFLIC or PO-ELIC models

### ISSUE THREAD

**Issue by jzyustc** [beiluo97/HFLIC#1]
Dear authors, thanks for your excellect works! 

I recently intended to utilize HFLIC for testing and evaluation purposes. Could you kindly consider releasing the pretrained HFLIC or PO-ELIC models if they are available? Your support would be greatly appreciated. Thank you very much!

**Comment by bdumoulin** [comment]
Hello,

I would also like to use HFLIC and/or PO-ELIC for testing purposes. Is it possible to release the trained models, it would be so great ! 

Thank you very much for you response :)

**Comment by beiluo97** [comment]
Hello,
Thank you for your patience. I've located the checkpoint files you inquired about. You can access them at the following link:
[EnhPO: ELIC and HFLIC Checkpoints](https://disk.pku.edu.cn/#/link/5DB382C6C7D49AAC0AC2E4D7FE31E9A2)
Please let me know if this is what you were looking for and if you encounter any issues while accessing or using the files. I'm here to help!
Best regards

**Comment by jzyustc** [comment]
> Hello, Thank you for your patience. I've located the checkpoint files you inquired about. You can access them at the following link: [EnhPO: ELIC and HFLIC Checkpoints](https://disk.pku.edu.cn/#/link/5DB382C6C7D49AAC0AC2E4D7FE31E9A2) Please let me know if this is what you were looking for and if you encounter any issues while accessing or using the files. I'm here to help! Best regards

Much thanks for your reply and the checkpoint!
